---
- name: configuring the {{component}} repo 
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo   # This ensure your source file to copy is non remote machine.

- name: installing {{component}}
  ansible.builtin.package:
    name: mongodb-org
    state: present    

- name: configuring the {{component}} visiblity
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'     

- name: starting {{component}}
  systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: download and extract {{component}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: injecting the {{component}} schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - users
    - catalogue
 
- name: configuring service
  ansible.builtin.shell: set-hostname "{{component}}-{{ENV}}"