- name: configuring the {{component}} repo 
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo   # This ensure your source file to copy is non remote machine.

- name: installing {{component}}
  ansible.builtin.package:
    name: mongodb-org
    state: present    

- name: starting {{ component }}
  systemd:
    name: mongodb
    state: restarted
    enabled: yes

- name: configuring service
  ansible.builtin.shell: set-hostname {{component}}-{{env}}