- name: configuring the {{component}} repo 
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo   # This ensure your source file to copy is non remote machine.

- name: installing mongodb 
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: reloaded mongodb 
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Replace old hostname with new hostname (requires Ansible >= 2.4)
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting {{component}}
  systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: download link
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: inhecting {{component}} schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - users
    - catalogue