# - name: demo on copy
#   hosts: all
#   become: yes   # sudo privilge
#   tasks:
#     - name: copying file with owner and permision
#       ansible.builtin.copy:
#         src: /home/centos/alt
#         dest: /home/centos/systemd.service
---
- hosts: dev
  tasks:
    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /home/centos/alt
        dest: /home/centos/
        mode: pull
      delegate_to: all