- name: demo on copy
  hosts: all
  become: yes   # sudo privilge
  tasks:
    - name: copying file
      copy:
        src: /tmp/pp.text #file in tmp directory of same machine
        dest: /home/centos/ansible/  #here we are giving destination where to copy in all the servers suppose
                                     #if we dont have the ansible directory/file it will create and move to the given destination  
      