- name: demo on copy
  hosts: all
  become: yes   # sudo privilge
  tasks:
    - name: copying file with owner and permision
      ansible.builtin.copy:
        src: touch
        dest: /home/centos/
      remote_src: yes