---
- name: demo on copy
  hosts: all
  become: yes   # sudo privilege
  tasks:
    - name: file
      copy:
        - src: /home/centos/alt
        - dest: /home/centos/
        - owner: centos
        - group: centos
        - mode: '0644'
      remote_src: yes  # Specify that the source file exists on the Ansible controller
