---
- name: demo on copy
  hosts: all
  become: yes   # sudo privilge
  tasks:
    - name: copying file with owner and permision
      ansible.builtin.copy:
        src: /home/centos/ali
        dest: /home/centos/