- name: demo on copy
  hosts: all
  become: yes   # sudo privilge
  tasks:
    - name: copying file
      ansible.builtin.copy:
        src: /home/centos/touch
        dest: /touch
        remote_src: yes  