- name: demo on conditions
  hosts: all
  vars: 
    action: true
  tasks: 
    - name: only run if the distribution is centos
      ansible.builtin.debug:
        msg: welcome to "{{ansible_distribution}}"
      when: ansible_distribution == "CentOS"  

    - name: only run if the distribution is ubuntu
      ansible.builtin.debug:
        msg: welcome to "{{ansible_distribution}}"
      when: ansible_distribution == "ubuntu"

    - name: run this action
      ansible.builtin.debug:
        msg: action is true
      when: action is true only display