- name: demo on copy
  hosts: all
  become: yes
  tasks:
    - name: copying file with owner and permision
      ansible.builtin.copy:
        src: system.service
        dest: /home/centos/systemd.service
