- name: demo on facts
  hosts: prod
  tasks:
    - name: printing the flavour of  prod machine
      ansible.builtin.debug:
        msg: server flavour is "{{ansible_distribution}}"  
    - name: printing the macaddress of machine
      ansible.builtin.debug:
        msg: server flavour is "{{ansible_deafault_ipv4.macaddress}}"      