- name: play1
  hosts: all
  tasks:    #parent
    - name: Printing hai from task1 of play1              #kids
      ansible.builtin.debug:
       msg: "hai maccha"

    - name: printing devops from tas2 of play1            #kids
      ansible.builtin.debug:
        msg: "devops real time project"   

- name: play2
  hosts: all
  tasks: 
     - name: Printing hai from task1 of play2
       ansible.builtin.debug:
        msg: "happy ganesha festivall"        