- name: demo on privilege  esclation
  hosts: all
  tasks:
    - name: checking user id 
      ansible.builtin.shell: id
      register: OUT

    - name: printing the uptime
      ansible.builtin.debug:
        msg: "{{OUT}}"  