- name: demo on shell
  hosts: all
  var: uptime
  tasks:
    - name: printing shell command
      ansible.builtin.shell: uptime
      register: time

    - name: printing the output value
      ansible.builtin.debug:
       msg: printing the variable "{{time}}" 