- name: demo on variable
  hosts: all
  vars:
    age: 27
  vars_prompt: 
    - name: age
      prompt: enter your name    
      private: false
  tasks: 
   - name: printing message of vars
     ansible.builtin.debug:
       msg: prem age is "{{age}}"

   - name: printing message of varsss
     ansible.builtin.debug:
       msg: prem age is "{{age}}"
     vars:
       age: 30 
  #  - name: Demo on using CLI age
  #    ansible.builtin.debug:
  #      msg: prem passing age is "{{CLI}}"    

