- name: demo on vars
  hosts: all
  vars:
    URL: play.google.com          #globall variable: all the tasks of the play can acess this variable
  tasks:
   - name: printing the variable
     ansible.builtin.debug:
        msg: value of the URL is {{URL}}   

   - name: Demo on using local variable
     ansible.builtin.debug:
        msg: value of the URL is {{URL}}
     vars:
       URL: FB.COM         

   - name: unrelated variable
     ansible.builtin.debug:
       msg: value of cURL is {{cURL}} 