- name: demo on variable
  hosts: all
  vars:
    age: 27  
  tasks: 
   - name: printing message of vars
     ansible.builtin.debug:
       msg: prem age is "{{age}}"

   - name: printing message of vars
     ansible.builtin.debug:
       msg: prem age is "{{age}}"
     vars:
       age: 30 

