- name: printing age
  hosts: production
  vars:
    age: 27
  tasks:
    - name: printing the age of prem
      ansible.builtin.debug:
        msg: prem age is"{{age}}"
        
    - name: local variable
      ansible.builtin.debug:
        msg: prem age is "{{age}}"
      vars: 
        age: 30       
        msg: prem age is "{{age}}""