---
- name: configuring the {{component}} repo 
  ansible.builtin.copy:
    src: mysql.repo.yml
    dest: /etc/yum.repos.d/{{component}}.repo   # This ensure your source file to copy is non remote machine.

- name: installing {{component}} 
  ansible.builtin.package:
    name: mysql-community-server 
    state: present

- name: starting {{component}}
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: fetches the log from the remote node
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: pwd_log 

- name: displaying the password
  ansible.builtin.debug:
    msg: "{{pwd_log}}"

- name: extracting the root password
  ansible.builtin.set_fact:
    DEFAULT_PASSWORD: "{{ pwd_log['content'] | b64decode | regex_findall('.*temporary password.*')| join('') | split(' ')| last }}"