---
- name: installing the url 
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -

- name: installing nodejs
  ansible.builtin.package:
    name: nodejs
    state: present
  
- name: creating "{{APPUSER}}"
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop app user

- name: download and extract "{{component}}"
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Performing {{component}} cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{component}}
    state: absent
  ignore_errors: yes

- name: copying the file to {{APPUSER}} home directory
  ansible.builtin.copy:
    src: /tmp/{{component}}-main
    dest: /home/{{APPUSER}}/
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes

- name: Install packages based on package.json.
  community.general.npm:
    path: /home/roboshop/{{component}}-main


- name: copying the systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{component}}.service
   
- name: starting service
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: configuring servicing name
  ansible.builtin.shell: set-hostname {{component}}-{{ENV}}