---
- name: installing the url 
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -

- name: installing Nodejs
  ansible.builtin.package:
    name: nodejs
    state: present
  
- name: creating {{APPUSER}}
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: downloading and extracting {{component}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: generating artifactwith npm install
  community.general.npm:
    path: /home/roboshop/{{component}}/

- name: config service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_service
